/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/scripts/generate/config-validator.ts
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { validateSiteConfig } from "./config-validator";

describe("config-validator", () => {
  describe("validateSiteConfig", () => {
    it("should be defined", () => {
      expect(typeof validateSiteConfig).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await validateSiteConfig(undefined);
      expect(result).toBeDefined();
    });
  });
});
