/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/ComparisonTable.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { ComparisonTable } from "./ComparisonTable.tsx";

describe("ComparisonTable.tsx", () => {
  describe("ComparisonTable", () => {
    it("should be defined", () => {
      expect(ComparisonTable).toBeDefined();
    });
  });
});
