/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/FAQSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { FAQSection } from "./FAQSection.tsx";

describe("FAQSection.tsx", () => {
  describe("FAQSection", () => {
    it("should be defined", () => {
      expect(FAQSection).toBeDefined();
    });
  });
});
