/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/SiteFooter.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { SiteFooter } from "./SiteFooter.tsx";

describe("SiteFooter.tsx", () => {
  describe("SiteFooter", () => {
    it("should be defined", () => {
      expect(SiteFooter).toBeDefined();
    });
  });
});
