/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/WhenToUseSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { WhenToUseSection } from "./WhenToUseSection.tsx";

describe("WhenToUseSection.tsx", () => {
  describe("WhenToUseSection", () => {
    it("should be defined", () => {
      expect(WhenToUseSection).toBeDefined();
    });
  });
});
