/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/HeroSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { HeroSection } from "./HeroSection.tsx";

describe("HeroSection.tsx", () => {
  describe("HeroSection", () => {
    it("should be defined", () => {
      expect(HeroSection).toBeDefined();
    });
  });
});
