/**
 * Auto-generated test file for vitest.config.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { defineConfig } from "./vitest.config";

describe("vitest.config", () => {
  describe("defineConfig", () => {
    it("should be defined", () => {
      expect(defineConfig).toBeDefined();
    });
  });
});
