/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/HowItWorksSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { HowItWorksSection } from "../../../../../../../../../common/themes/odins-innovations/components/shared/HowItWorksSection.tsx";

describe("HowItWorksSection.tsx", () => {
  describe("HowItWorksSection", () => {
    it("should be defined", () => {
      expect(HowItWorksSection).toBeDefined();
    });
  });
});
