/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/HowToUseSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { HowToUseSection } from "../../../../../../../../../common/themes/odins-innovations/components/shared/HowToUseSection.tsx";

describe("HowToUseSection.tsx", () => {
  describe("HowToUseSection", () => {
    it("should be defined", () => {
      expect(HowToUseSection).toBeDefined();
    });
  });
});
