/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/ServicesSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { ServicesSection } from "../../../../../../../../../common/themes/odins-innovations/components/shared/ServicesSection.tsx";

describe("ServicesSection.tsx", () => {
  describe("ServicesSection", () => {
    it("should be defined", () => {
      expect(ServicesSection).toBeDefined();
    });
  });
});
