/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/TrustBarSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { TrustBarSection } from "../../../../../../../../../common/themes/odins-innovations/components/shared/TrustBarSection.tsx";

describe("TrustBarSection.tsx", () => {
  describe("TrustBarSection", () => {
    it("should be defined", () => {
      expect(TrustBarSection).toBeDefined();
    });
  });
});
