/**
 * Auto-generated test file for common/plugins/base-path-plugin.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { basePathPlugin } from "./base-path-plugin";

describe("base-path-plugin", () => {
  describe("basePathPlugin", () => {
    it("should be defined", () => {
      expect(typeof basePathPlugin).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await basePathPlugin("test");
      expect(result).toBeDefined();
    });
  });
});
