/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/scripts/generate-site.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { defineConfig } from "../../../../../scripts/generate-site";

describe("generate-site", () => {
  describe("defineConfig", () => {
    it("should be defined", () => {
      expect(defineConfig).toBeDefined();
    });
  });
});
