/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/MosquitoSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { MosquitoSection } from "./MosquitoSection.tsx";

describe("MosquitoSection.tsx", () => {
  describe("MosquitoSection", () => {
    it("should be defined", () => {
      expect(MosquitoSection).toBeDefined();
    });
  });
});
