/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/ProductsSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { ProductsSection } from "./ProductsSection.tsx";

describe("ProductsSection.tsx", () => {
  describe("ProductsSection", () => {
    it("should be defined", () => {
      expect(ProductsSection).toBeDefined();
    });
  });
});
