/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/components/shared/WhyOdinsSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { WhyOdinsSection } from "./WhyOdinsSection.tsx";

describe("WhyOdinsSection.tsx", () => {
  describe("WhyOdinsSection", () => {
    it("should be defined", () => {
      expect(WhyOdinsSection).toBeDefined();
    });
  });
});
