/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/utils/grid-layout.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { getColumnSpanClass, getColumnClass, getGridLayoutClasses } from "../../../../../../common/utils/grid-layout";

describe("grid-layout", () => {
  describe("getColumnSpanClass", () => {
    it("should be defined", () => {
      expect(typeof getColumnSpanClass).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await getColumnSpanClass(1);
      expect(typeof result).toBe('string');
    });
  });

  describe("getColumnClass", () => {
    it("should be defined", () => {
      expect(typeof getColumnClass).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await getColumnClass(1, 1);
      expect(typeof result).toBe('string');
    });
  });

  describe("getGridLayoutClasses", () => {
    it("should be defined", () => {
      expect(typeof getGridLayoutClasses).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await getGridLayoutClasses(1);
      expect(typeof result).toBe('string');
    });
  });
});
