/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/contexts/BrandContext.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { BrandProvider, useBrand, getDefaultBrandContext, useBrandName, useBrandUrls, useBrandContact, useBrandSocial, usePromoCode, useAppUrl } from "../../../../../../common/contexts/BrandContext.tsx";

describe("BrandContext.tsx", () => {
  describe("BrandProvider", () => {
    it("should be defined", () => {
      expect(typeof BrandProvider).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await BrandProvider(undefined, undefined, undefined, undefined, undefined, undefined);
      expect(result).toBeUndefined();
    });
  });

  describe("useBrand", () => {
    it("should be defined", () => {
      expect(typeof useBrand).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await useBrand();
      expect(result).toBeDefined();
    });
  });

  describe("getDefaultBrandContext", () => {
    it("should be defined", () => {
      expect(typeof getDefaultBrandContext).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await getDefaultBrandContext();
      expect(result).toBeDefined();
    });
  });

  describe("useBrandName", () => {
    it("should be defined", () => {
      expect(typeof useBrandName).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await useBrandName();
      expect(typeof result).toBe('string');
    });
  });

  describe("useBrandUrls", () => {
    it("should be defined", () => {
      expect(typeof useBrandUrls).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await useBrandUrls();
      expect(result).toBeDefined();
    });
  });

  describe("useBrandContact", () => {
    it("should be defined", () => {
      expect(typeof useBrandContact).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await useBrandContact();
      expect(result).toBeDefined();
    });
  });

  describe("useBrandSocial", () => {
    it("should be defined", () => {
      expect(typeof useBrandSocial).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await useBrandSocial();
      expect(result).toBeDefined();
    });
  });

  describe("usePromoCode", () => {
    it("should be defined", () => {
      expect(typeof usePromoCode).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await usePromoCode();
      expect(typeof result).toBe('string');
    });
  });

  describe("useAppUrl", () => {
    it("should be defined", () => {
      expect(typeof useAppUrl).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await useAppUrl();
      expect(typeof result).toBe('string');
    });
  });
});
