/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/AboutSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { AboutSection } from "../../../../../../../common/components/shared/AboutSection.tsx";

describe("AboutSection.tsx", () => {
  describe("AboutSection", () => {
    it("should be defined", () => {
      expect(AboutSection).toBeDefined();
    });
  });
});
