/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/BrandStorySection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { BrandStorySection } from "../../../../../../../common/components/shared/BrandStorySection.tsx";

describe("BrandStorySection.tsx", () => {
  describe("BrandStorySection", () => {
    it("should be defined", () => {
      expect(BrandStorySection).toBeDefined();
    });
  });
});
