/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/BusinessContinuitySection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { BusinessContinuitySection } from "../../../../../../../common/components/shared/BusinessContinuitySection.tsx";

describe("BusinessContinuitySection.tsx", () => {
  describe("BusinessContinuitySection", () => {
    it("should be defined", () => {
      expect(BusinessContinuitySection).toBeDefined();
    });
  });
});
