/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/CaseStudiesSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { CaseStudiesSection } from "../../../../../../../common/components/shared/CaseStudiesSection.tsx";

describe("CaseStudiesSection.tsx", () => {
  describe("CaseStudiesSection", () => {
    it("should be defined", () => {
      expect(CaseStudiesSection).toBeDefined();
    });
  });
});
