/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/ComparisonChartSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { ComparisonChartSection } from "../../../../../../../common/components/shared/ComparisonChartSection.tsx";

describe("ComparisonChartSection.tsx", () => {
  describe("ComparisonChartSection", () => {
    it("should be defined", () => {
      expect(ComparisonChartSection).toBeDefined();
    });
  });
});
