/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/ComparisonSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { ComparisonSection } from "../../../../../../../common/components/shared/ComparisonSection.tsx";

describe("ComparisonSection.tsx", () => {
  describe("ComparisonSection", () => {
    it("should be defined", () => {
      expect(ComparisonSection).toBeDefined();
    });
  });
});
