/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/DifferenceSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { DifferenceSection } from "../../../../../../../common/components/shared/DifferenceSection.tsx";

describe("DifferenceSection.tsx", () => {
  describe("DifferenceSection", () => {
    it("should be defined", () => {
      expect(DifferenceSection).toBeDefined();
    });
  });
});
