/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/HighlightSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { HighlightSection, HighlightSection } from "../../../../../../../common/components/shared/HighlightSection.tsx";

describe("HighlightSection.tsx", () => {
  describe("HighlightSection", () => {
    it("should be defined", () => {
      expect(typeof HighlightSection).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await HighlightSection(undefined);
      expect(result).toBeUndefined();
    });
  });

  describe("HighlightSection", () => {
    it("should be defined", () => {
      expect(HighlightSection).toBeDefined();
    });
  });
});
