/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/PricingSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { PricingSection } from "../../../../../../../common/components/shared/PricingSection.tsx";

describe("PricingSection.tsx", () => {
  describe("PricingSection", () => {
    it("should be defined", () => {
      expect(PricingSection).toBeDefined();
    });
  });
});
