/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/ProductsCategoriesSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { ProductsCategoriesSection } from "../../../../../../../common/components/shared/ProductsCategoriesSection.tsx";

describe("ProductsCategoriesSection.tsx", () => {
  describe("ProductsCategoriesSection", () => {
    it("should be defined", () => {
      expect(ProductsCategoriesSection).toBeDefined();
    });
  });
});
