/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/ReviewsSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { ReviewsSection } from "../../../../../../../common/components/shared/ReviewsSection.tsx";

describe("ReviewsSection.tsx", () => {
  describe("ReviewsSection", () => {
    it("should be defined", () => {
      expect(ReviewsSection).toBeDefined();
    });
  });
});
