/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/SiteNavigation.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { SiteNavigation } from "../../../../../../../common/components/shared/SiteNavigation.tsx";

describe("SiteNavigation.tsx", () => {
  describe("SiteNavigation", () => {
    it("should be defined", () => {
      expect(SiteNavigation).toBeDefined();
    });
  });
});
