/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/SiteFooter.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { SiteFooter } from "../../../../../../../common/components/shared/SiteFooter.tsx";

describe("SiteFooter.tsx", () => {
  describe("SiteFooter", () => {
    it("should be defined", () => {
      expect(SiteFooter).toBeDefined();
    });
  });
});
