/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/TestimonialsSection.tsx
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { TestimonialsSection } from "../../../../../../../common/components/shared/TestimonialsSection.tsx";

describe("TestimonialsSection.tsx", () => {
  describe("TestimonialsSection", () => {
    it("should be defined", () => {
      expect(TestimonialsSection).toBeDefined();
    });
  });
});
