/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/components/shared/TrustBadgesSection.tsx
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { TrustBadgesSection } from "../../../../../../../common/components/shared/TrustBadgesSection.tsx";

describe("TrustBadgesSection.tsx", () => {
  describe("TrustBadgesSection", () => {
    it("should be defined", () => {
      expect(TrustBadgesSection).toBeDefined();
    });
  });
});
