/**
 * Auto-generated test file for common/vite-env.d.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { content } from "./vite-env.d";

describe("vite-env.d", () => {
  describe("content", () => {
    it("should be defined", () => {
      expect(content).toBeDefined();
    });
  });
});
