#!/usr/bin/env npx tsx
/**
 * Bundle built Odin's sites for manual Shopify upload.
 *
 * Usage:
 *   npx tsx scripts/bundle-odins-deploy.ts
 *   npx tsx scripts/bundle-odins-deploy.ts --service synthetic-scent-cwd-guide
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const BRAND = 'odins-innovations';
const SITES_DIR = path.join(ROOT, 'sites', BRAND);
const OUT_DIR = path.join(ROOT, 'deploy', BRAND);
const URL_MAP = JSON.parse(
  fs.readFileSync(path.join(__dirname, 'odins-live-urls.json'), 'utf8')
) as {
  baseUrl: string;
  sites: Record<string, { liveUrl: string | null; notes?: string }>;
};

const args = process.argv.slice(2);
const onlyService = (() => {
  const idx = args.indexOf('--service');
  return idx >= 0 ? args[idx + 1] : null;
})();

function listServices(): string[] {
  return fs
    .readdirSync(path.join(ROOT, 'config', 'sites', BRAND))
    .filter((f) => f.endsWith('.json') && !f.includes('.backup'))
    .map((f) => f.replace(/\.json$/, ''))
    .sort();
}

function copyDir(src: string, dest: string): number {
  if (!fs.existsSync(src)) return 0;
  fs.mkdirSync(dest, { recursive: true });
  let count = 0;
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const from = path.join(src, entry.name);
    const to = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      count += copyDir(from, to);
    } else {
      fs.copyFileSync(from, to);
      count += 1;
    }
  }
  return count;
}

function bundleService(service: string): { ok: boolean; message: string } {
  const siteDir = path.join(SITES_DIR, service);
  const distAssets = path.join(siteDir, 'dist', 'assets');
  const shopifyHtml = path.join(siteDir, 'shopify.html');
  const outService = path.join(OUT_DIR, service);

  if (!fs.existsSync(shopifyHtml)) {
    return { ok: false, message: 'missing shopify.html — run build:shopify:odins first' };
  }

  fs.rmSync(outService, { recursive: true, force: true });
  fs.mkdirSync(outService, { recursive: true });

  const assetCount = copyDir(distAssets, path.join(outService, 'assets'));
  fs.copyFileSync(shopifyHtml, path.join(outService, 'shopify.html'));

  const html = fs.readFileSync(shopifyHtml, 'utf8');
  const css = html.match(/index-[A-Za-z0-9_-]+\.css/)?.[0] ?? '—';
  const js = html.match(/index-[A-Za-z0-9_-]+\.js/)?.[0] ?? '—';
  const rootMatch = html.match(/<div id="root">([\s\S]*?)<\/div>\s*(?:<style|{{ content_for_footer)/);
  const prerenderBytes = rootMatch ? rootMatch[1].trim().length : 0;

  const live = URL_MAP.sites[service];
  const checklist = [
    `# Deploy: ${service}`,
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    '## Artifacts',
    `- \`shopify.html\` — paste into Shopify page liquid template`,
    `- \`assets/\` — upload ${assetCount} file(s) to Shopify Files (same filenames)`,
    `- CSS hash: \`${css}\``,
    `- JS hash: \`${js}\``,
    `- Prerender #root: ${prerenderBytes.toLocaleString()} bytes`,
    '',
    '## Live target',
    live?.liveUrl ? `- URL: ${live.liveUrl}` : '- URL: (no mapped live page — create or map in odins-live-urls.json)',
    live?.notes ? `- Notes: ${live.notes}` : '',
    '',
    '## Steps',
    '1. Shopify Admin → Content → Files → upload everything in `assets/`',
    '2. Shopify Admin → Online Store → Pages → open target page → Edit code',
    '3. Replace page template liquid body with contents of `shopify.html`',
    '4. Save and preview; confirm #root has prerendered HTML (View Source)',
    '5. Run `npm run audit:odins-live` to verify asset hashes match live',
    '',
  ].join('\n');

  fs.writeFileSync(path.join(outService, 'DEPLOY.md'), checklist);
  return {
    ok: prerenderBytes > 500,
    message: `${assetCount} assets, prerender ${prerenderBytes} bytes`,
  };
}

function main(): void {
  const services = onlyService ? [onlyService] : listServices();
  console.log(`\n📦 Bundling ${services.length} Odin's deploy package(s) → deploy/${BRAND}/\n`);

  let ok = 0;
  let warn = 0;
  let fail = 0;

  for (const service of services) {
    const result = bundleService(service);
    const icon = result.ok ? '✅' : result.message.includes('missing') ? '❌' : '⚠️';
    console.log(`${icon} ${service}: ${result.message}`);
    if (result.message.includes('missing')) fail += 1;
    else if (result.ok) ok += 1;
    else warn += 1;
  }

  console.log(`\nDone: ${ok} ready, ${warn} low prerender, ${fail} failed\n`);
  fs.writeFileSync(
    path.join(OUT_DIR, 'README.md'),
    [
      '# Odin\'s Innovations — Shopify Deploy Bundles',
      '',
      `Generated by \`npm run bundle:odins-deploy\` on ${new Date().toISOString().split('T')[0]}.`,
      '',
      'Each subdirectory contains:',
      '- `shopify.html` — liquid template for the Shopify page',
      '- `assets/` — hashed JS/CSS (and any other built assets)',
      '- `DEPLOY.md` — per-site checklist with live URL and asset hashes',
      '',
      '**Workflow:** `npm run build:shopify:odins` → `npm run bundle:odins-deploy` → manual Shopify upload → `npm run audit:odins-live`',
      '',
    ].join('\n')
  );
}

main();