/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/common/themes/odins-innovations/config/brand.ts
 * Generated by 0xRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { odinsBrandConfig } from "./brand";

describe("brand", () => {
  describe("odinsBrandConfig", () => {
    it("should be defined", () => {
      expect(odinsBrandConfig).toBeDefined();
    });
  });
});
