/**
 * Auto-generated test file for /Users/henrytafolla/dev/template-microsite/sites/odins-innovations/synthetic-scent-cwd-guide/vite.config.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { defineConfig } from "../../../../../../../sites/odins-innovations/synthetic-scent-cwd-guide/vite.config";

describe("vite.config", () => {
  describe("defineConfig", () => {
    it("should be defined", () => {
      expect(defineConfig).toBeDefined();
    });
  });
});
