/**
 * Auto-generated test file for common/utils/sanitize-html.ts
 * Generated by StringRay TestAutoCreationProcessor
 * @generated
 */

import { describe, it, expect } from "vitest";
import { sanitizeHtml } from "./sanitize-html";

describe("sanitize-html", () => {
  describe("sanitizeHtml", () => {
    it("should be defined", () => {
      expect(typeof sanitizeHtml).toBe("function");
    });

    it("should handle basic case", async () => {
      const result = await sanitizeHtml("test");
      expect(typeof result).toBe('string');
    });
  });
});
